name: Convert JSON to M3U

on:
  push:
    paths:
      - channels.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Convert JSON to M3U
      run: |
        python -c "
import json

# Carregar o arquivo JSON
with open('channels.json', 'r') as file:
    channels = json.load(file)

# Criar o conteúdo M3U
m3u_content = '#EXTM3U\\n'

for channel in channels:
    tvg_id = channel['tvg_id'] if channel['tvg_id'] else ''
    logo = channel['logo'] if channel['logo'] else ''
    m3u_content += f'#EXTINF:-1 tvg-id=\\"{tvg_id}\\" tvg-logo=\\"{logo}\\" group-title=\\"{channel['group']}\",{channel['name']}\\n'
    m3u_content += f'{channel['url']}\\n'

# Salvar o conteúdo M3U em um arquivo
with open('playlist.m3u', 'w') as file:
    file.write(m3u_content)
"

    - name: Commit and push M3U
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add playlist.m3u
        git commit -m "Update M3U playlist"
        git push
